# generated by packages/contract/scripts/generate-inference-tunings.mjs - do not edit.
# Source of truth: the "inference" section of packages/contract/config.json.
# Regenerate with: moon run contract:generateTunings

CTC: dict[str, object] = {
    "alpha": 1.6,
    "beta": 2,
    "unk_score_offset": -10,
    "beam_width": 50,
    "beam_prune_logp": -10,
    "token_min_logp": -5,
    "confidence_temperature": 2.279,
    "hotwords": ("aadi", "chad", "shiven"),
    "hotword_weight": 8,
}

SMOOTH: dict[str, object] = {
    "display_confidence": 0.101,
    "display_streak": 1,
    "display_count": 1,
    "display_clear_misses": 1,
    "display_clear_motion": 0.003,
    "instant_display_confidence": 0.721,
    "commit_confidence": 0.853,
    "short_commit_confidence": 0.921,
    "commit_streak": 5,
    "commit_count": 7,
    "endpoint_commit_count": 1,
    "commit_soft_oov_min_chars": 7,
    "commit_soft_oov_confidence": 0.765,
    "commit_reject_uncorrected_oov_chars": 8,
    "stable_commit_confidence": 0.949,
    "stable_commit_count": 14,
    "stable_commit_streak": 11,
    "stable_commit_min_chars": 3,
    "short_stable_commit_confidence": 0.594,
    "short_stable_commit_count": 15,
    "short_stable_commit_streak": 14,
    "short_stable_commit_min_chars": 2,
    "short_stable_commit_max_chars": 3,
    "majority_commit_min_count": 26,
    "majority_commit_min_share": 0.73,
    "majority_commit_min_chars": 2,
    "alternative_commit_confidence": 0.178,
    "alternative_commit_count": 22,
    "alternative_commit_min_chars": 4,
    "alternative_commit_recent_misses": 6,
    "replace_margin": -0.041,
}
