# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, Field, RootModel


class DecodeCfg(BaseModel):
    window: Annotated[int, Field(ge=8, le=512)]


class DecodeTrace(BaseModel):
    buffered_frames: int
    input_text: str
    display_text: str
    idle_frames: int
    motion: float
    latency_ms: float


class EndpointReason(Enum):
    idle = "idle"
    landmark_lost = "landmark-lost"


class FinalizeTrace(BaseModel):
    text: str
    confidence: float
    committed: bool
    endpoint_reason: EndpointReason
    segment_frames: int


class HealthOut(BaseModel):
    ok: bool


class LandmarkFrame(RootModel[list[float]]):
    root: Annotated[list[float], Field(max_length=162, min_length=162)]


class PredictIn(BaseModel):
    frames: Annotated[list[LandmarkFrame], Field(max_length=512, min_length=1)]


class Prediction(BaseModel):
    label: str
    confidence: Annotated[float, Field(ge=0.0, le=1.0)]
    logit_score: float | None = None
    lm_score: float | None = None
    raw_label: str | None = None


class RecognitionContext(BaseModel):
    idle_frames: Annotated[int, Field(ge=0)]
    missing_frames: Annotated[int, Field(ge=0)]
    segment_frames: Annotated[int, Field(ge=0)]
    motion: Annotated[float, Field(ge=0.0)]
    endpoint_reason: EndpointReason | None = None


class RecognitionCount(BaseModel):
    text: str
    count: int


class RecognitionScored(BaseModel):
    prediction: Prediction
    score: float
    source: str
    lm_score: float | None = None
    model_agrees: bool
    streak: int


class RecognitionState(BaseModel):
    display: RecognitionScored | None = None
    final_candidate: RecognitionScored | None = None
    alternative_candidate: RecognitionScored | None = None
    selected_text: str
    selected_streak: int
    display_misses: int
    counts: list[RecognitionCount]
    alternative_counts: list[RecognitionCount] | None = None
    alternative_misses: int | None = None


class RecognizeIn(BaseModel):
    frames: Annotated[list[LandmarkFrame] | None, Field(max_length=512)] = None
    state: RecognitionState | None = None
    context: RecognitionContext
    finalize: bool | None = None


class SmoothCfg(BaseModel):
    freq: Annotated[float, Field(ge=0.0)]
    cutoff: Annotated[float, Field(ge=0.0)]
    beta: Annotated[float, Field(ge=0.0)]
    dCutoff: Annotated[float, Field(ge=0.0)]


class SmoothSet(BaseModel):
    hand: SmoothCfg
    pose: SmoothCfg


class Span(BaseModel):
    start_frame: int
    end_frame: int
    text: str


class StreamCfg(BaseModel):
    fps: Annotated[int, Field(ge=1)]
    min: Annotated[int, Field(ge=1)]
    stride: Annotated[int, Field(ge=1)]
    idle: Annotated[int, Field(ge=1)]
    lost: Annotated[int, Field(ge=1)]
    holdMs: Annotated[int, Field(ge=1)]
    motion: Annotated[float, Field(ge=0.0)]


class MpCfg(BaseModel):
    smooth: SmoothSet


class PredictOut(BaseModel):
    prediction: Prediction
    alternatives: list[Prediction]
    spans: list[Span]
    greedy_text: str
    blank_ratio: Annotated[float, Field(ge=0.0, le=1.0)]
    tail_blank_ratio: Annotated[float, Field(ge=0.0, le=1.0)]
    tail_blank_frames: int
    partial_text: str
    stable_text: str


class RecognitionTrace(BaseModel):
    prediction: PredictOut | None = None
    decode: DecodeTrace | None = None
    finalize: FinalizeTrace | None = None


class RecognizeOut(BaseModel):
    state: RecognitionState
    display_prediction: Prediction | None = None
    committed: bool
    trace: RecognitionTrace


class Config(BaseModel):
    decode: DecodeCfg
    stream: StreamCfg
    mp: MpCfg
