import { spawnSync } from "node:child_process";
import { cp, mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { readContract } from "./validate.mjs";

const root = path.resolve(fileURLToPath(new URL("..", import.meta.url)));
const workspaceRoot = path.resolve(root, "../..");

const generatedNotice = "Generated by packages/contract/scripts/generate.mjs.";
await rm(path.join(root, "generated"), { recursive: true, force: true });
compileTypeSpec();
const contract = await readContract();

await writeGeneratedFile(
  path.join(root, "src/generated.ts"),
  [
    `// ${generatedNotice}`,
    "",
    `export const cfg = ${JSON.stringify(contract, null, 2)} as const;`,
    "",
    "export type Cfg = typeof cfg;",
    "",
  ].join("\n"),
);

await writeGeneratedFile(
  path.join(
    workspaceRoot,
    "apps/mobile/HandWave/Sources/Generated/InferCfg.swift",
  ),
  swiftConfiguration(contract),
);

generateWebClient();
generatePythonSchemas();
formatPythonSchemas();
await generateSwiftModels();
formatContractOutput();

async function writeGeneratedFile(filePath, content) {
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, content);
}

function swiftConfiguration(config) {
  return [
    `// ${generatedNotice}`,
    "import Foundation",
    "",
    "enum InferCfg {",
    "  enum Decode {",
    `    static let window = ${config.decode.window}`,
    "  }",
    "",
    "  enum Stream {",
    `    static let fps = ${config.stream.fps}`,
    `    static let min = ${config.stream.min}`,
    `    static let stride = ${config.stream.stride}`,
    `    static let idle = ${config.stream.idle}`,
    `    static let lost = ${config.stream.lost}`,
    `    static let holdMs = ${config.stream.holdMs}`,
    `    static let motion = ${swiftNumber(config.stream.motion)}`,
    "  }",
    "",
    "  enum MP {",
    "    enum Smooth {",
    swiftSmoothing("Hand", config.mp.smooth.hand),
    "",
    swiftSmoothing("Pose", config.mp.smooth.pose),
    "    }",
    "  }",
    "}",
    "",
  ].join("\n");
}

function swiftSmoothing(name, config) {
  return [
    `      enum ${name} {`,
    `        static let freq = ${swiftNumber(config.freq)}`,
    `        static let cutoff = ${swiftNumber(config.cutoff)}`,
    `        static let beta = ${swiftNumber(config.beta)}`,
    `        static let dCutoff = ${swiftNumber(config.dCutoff)}`,
    "      }",
  ].join("\n");
}

function swiftNumber(value) {
  return Number.isInteger(value) ? `${value}.0` : String(value);
}

function compileTypeSpec() {
  const result = spawnSync("pnpm", ["exec", "tsp", "compile", "."], {
    cwd: root,
    stdio: "inherit",
  });

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

function generateWebClient() {
  const result = spawnSync(
    "pnpm",
    [
      "--dir",
      path.join(workspaceRoot, "apps/web"),
      "exec",
      "openapi-typescript",
      path.join(root, "generated/openapi/openapi.json"),
      "-o",
      path.join(workspaceRoot, "apps/web/src/lib/inference/openapi.ts"),
    ],
    {
      cwd: root,
      stdio: "inherit",
    },
  );

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

function generatePythonSchemas() {
  const result = spawnSync(
    "uv",
    [
      "run",
      "--project",
      path.join(workspaceRoot, "apps/inference"),
      "--group",
      "dev",
      "datamodel-codegen",
      "--input",
      path.join(root, "generated/openapi/openapi.json"),
      "--input-file-type",
      "openapi",
      "--output-model-type",
      "pydantic_v2.BaseModel",
      "--field-constraints",
      "--use-annotated",
      "--disable-timestamp",
      "--output",
      path.join(
        workspaceRoot,
        "apps/inference/src/inference/generated_schemas.py",
      ),
    ],
    {
      cwd: root,
      stdio: "inherit",
    },
  );

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

function formatPythonSchemas() {
  const result = spawnSync(
    "uv",
    [
      "run",
      "--project",
      path.join(workspaceRoot, "apps/inference"),
      "--group",
      "dev",
      "ruff",
      "format",
      path.join(
        workspaceRoot,
        "apps/inference/src/inference/generated_schemas.py",
      ),
    ],
    {
      cwd: root,
      stdio: "inherit",
    },
  );

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

async function generateSwiftModels() {
  const output = await mkdtemp(path.join(tmpdir(), "handwave-openapi-swift-"));
  const target = path.join(
    workspaceRoot,
    "apps/mobile/HandWave/Sources/Generated/OpenAPI",
  );

  try {
    const result = spawnSync(
      "pnpm",
      [
        "exec",
        "openapi-generator-cli",
        "generate",
        "-g",
        "swift6",
        "-i",
        path.join(root, "generated/openapi/openapi.json"),
        "-o",
        output,
        "--global-property",
        "models,modelDocs=false,modelTests=false,apis=false,supportingFiles=false",
        "--additional-properties",
        [
          "responseAs=AsyncAwait",
          "projectName=HandWaveInference",
          "generateAliasAsModel=true",
          "validatable=false",
          "modelNamePrefix=Inference",
        ].join(","),
      ],
      {
        cwd: root,
        stdio: "inherit",
      },
    );

    if (result.status !== 0) {
      process.exit(result.status ?? 1);
    }

    await rm(target, { recursive: true, force: true });
    await mkdir(target, { recursive: true });
    await cp(path.join(output, "Sources/HandWaveInference/Models"), target, {
      recursive: true,
    });
    formatSwiftModels(target);
  } finally {
    await rm(output, { recursive: true, force: true });
  }
}

function formatSwiftModels(target) {
  const result = spawnSync(
    "swift",
    ["format", "--recursive", "--in-place", target],
    {
      cwd: workspaceRoot,
      stdio: "inherit",
    },
  );

  if (result.error?.code === "ENOENT") {
    return;
  }

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

function formatContractOutput() {
  const result = spawnSync(
    "pnpm",
    [
      "exec",
      "oxfmt",
      "--write",
      "generated",
      "src/generated.ts",
      path.join(workspaceRoot, "apps/web/src/lib/inference/openapi.ts"),
    ],
    {
      cwd: root,
      stdio: "inherit",
    },
  );

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}
