import { spawnSync } from "node:child_process";
import { mkdir, rm, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { readContract } from "./validate.mjs";

const root = path.resolve(fileURLToPath(new URL("..", import.meta.url)));
const workspaceRoot = path.resolve(root, "../..");

const generatedNotice = "Generated by packages/contract/scripts/generate.mjs.";
await rm(path.join(root, "generated"), { recursive: true, force: true });
compileTypeSpec();
const contract = await readContract();

await writeGeneratedFile(
  path.join(root, "src/generated.ts"),
  [
    `// ${generatedNotice}`,
    "",
    `export const cfg = ${JSON.stringify(contract, null, 2)} as const;`,
    "",
    "export type Cfg = typeof cfg;",
    "",
  ].join("\n"),
);

await writeGeneratedFile(
  path.join(
    workspaceRoot,
    "apps/mobile/HandWave/Sources/Generated/InferCfg.swift",
  ),
  swiftConfiguration(contract),
);

await writeGeneratedFile(
  path.join(workspaceRoot, "apps/inference/src/inference/contract.py"),
  pythonConfiguration(contract),
);

async function writeGeneratedFile(filePath, content) {
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, content);
}

function swiftConfiguration(config) {
  return [
    `// ${generatedNotice}`,
    "import Foundation",
    "",
    "enum InferCfg {",
    "  enum Session {",
    `    static let window = ${config.session.window}`,
    `    static let stable = ${config.session.stable}`,
    "  }",
    "",
    "  enum Stream {",
    `    static let fps = ${config.stream.fps}`,
    `    static let min = ${config.stream.min}`,
    `    static let stride = ${config.stream.stride}`,
    `    static let idle = ${config.stream.idle}`,
    `    static let lost = ${config.stream.lost}`,
    `    static let holdMs = ${config.stream.holdMs}`,
    `    static let motion = ${swiftNumber(config.stream.motion)}`,
    "  }",
    "",
    "  enum MP {",
    "    enum Smooth {",
    swiftSmoothing("Hand", config.mp.smooth.hand),
    "",
    swiftSmoothing("Pose", config.mp.smooth.pose),
    "    }",
    "  }",
    "}",
    "",
  ].join("\n");
}

function swiftSmoothing(name, config) {
  return [
    `      enum ${name} {`,
    `        static let freq = ${swiftNumber(config.freq)}`,
    `        static let cutoff = ${swiftNumber(config.cutoff)}`,
    `        static let beta = ${swiftNumber(config.beta)}`,
    `        static let dCutoff = ${swiftNumber(config.dCutoff)}`,
    "      }",
  ].join("\n");
}

function swiftNumber(value) {
  return Number.isInteger(value) ? `${value}.0` : String(value);
}

function compileTypeSpec() {
  const result = spawnSync("pnpm", ["exec", "tsp", "compile", "."], {
    cwd: root,
    stdio: "inherit",
  });

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

function pythonConfiguration(config) {
  return [
    `# ${generatedNotice}`,
    "",
    `SESSION_WINDOW = ${config.session.window}`,
    `SESSION_STABLE = ${config.session.stable}`,
    "",
    `STREAM_FPS = ${config.stream.fps}`,
    `STREAM_MIN = ${config.stream.min}`,
    `STREAM_STRIDE = ${config.stream.stride}`,
    `STREAM_IDLE = ${config.stream.idle}`,
    `STREAM_LOST = ${config.stream.lost}`,
    `STREAM_HOLD_MS = ${config.stream.holdMs}`,
    `STREAM_MOTION = ${config.stream.motion}`,
    "",
    `MP_HAND_SMOOTH = ${pythonDict(config.mp.smooth.hand)}`,
    `MP_POSE_SMOOTH = ${pythonDict(config.mp.smooth.pose)}`,
    "",
  ].join("\n");
}

function pythonDict(value) {
  return JSON.stringify(value, null, 2)
    .replaceAll('"', "'")
    .replace(/: ([\d.]+)/g, ": $1")
    .replace(/^  /gm, "    ");
}
