"""Shared endpoint checks and generated client configuration for our launchers."""

from __future__ import annotations

import asyncio
import json
from pathlib import Path
from urllib.parse import urlsplit

import aiohttp

ROOT = Path(__file__).resolve().parents[3]


def validate_url(url: str) -> str:
    parsed = urlsplit(url)
    if (
        parsed.scheme != "https"
        or not parsed.hostname
        or parsed.username
        or parsed.password
        or parsed.port
        or parsed.path not in ("", "/")
        or parsed.query
        or parsed.fragment
        or any(character.isspace() for character in url)
    ):
        raise ValueError("Expected an HTTPS inference service origin")
    return url.rstrip("/")


def write_endpoint(url: str, configuration: str) -> Path:
    """The credential file cannot override these generated settings."""
    url = validate_url(url)
    if configuration not in ("Debug", "Release"):
        raise ValueError("Unknown Xcode configuration")
    path = ROOT / f"apps/mobile/Configurations/{configuration}Endpoint.xcconfig"
    contents = "// Generated by Hand Wave tooling. Do not edit.\n"
    contents += f"HANDWAVE_INFERENCE_URL = {url.replace('://', ':/$()/')}\n"
    temporary = path.with_suffix(".tmp")
    temporary.write_text(contents)
    temporary.replace(path)
    return path


async def verify_backend(url: str, deployment_id: str) -> None:
    """Wait for the real model, then test the protocol used by both clients."""
    url = validate_url(url)
    async with (
        asyncio.timeout(180),
        aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=20)) as client,
    ):
        while True:
            try:
                async with client.get(f"{url}/v1/health") as response:
                    response.raise_for_status()
                    health = await response.json()
                break
            except (aiohttp.ClientError, TimeoutError):
                await asyncio.sleep(2)
        if health.get("ok") is not True or health.get("deployment_id") != deployment_id:
            raise RuntimeError("The endpoint does not belong to this backend build")
        async with client.ws_connect(
            f"wss://{urlsplit(url).netloc}/v1/stream", protocols=["handwave.v1"]
        ) as socket:
            await socket.send_json({"type": "ping", "sequence": 1, "protocol": 1})
            pong = await socket.receive_json()
            if pong != {"type": "pong", "sequence": 1, "protocol": 1}:
                raise RuntimeError(f"Invalid inference handshake: {pong}")
            await socket.send_json(
                {
                    "type": "recognize",
                    "sequence": 2,
                    "protocol": 1,
                    "frames": [[0.0] * 162 for _ in range(24)],
                    "context": {
                        "idle_frames": 0,
                        "missing_frames": 0,
                        "segment_frames": 24,
                        "motion": 0.0,
                    },
                    "finalize": True,
                }
            )
            result = await socket.receive_json()
            if result.get("type") != "result" or result.get("sequence") != 2:
                raise RuntimeError(f"Inference smoke test failed: {result}")
            await socket.send_json({"type": "reset", "sequence": 3, "protocol": 1})
            reset = await socket.receive_json()
            if reset != {"type": "reset", "sequence": 3, "protocol": 1}:
                raise RuntimeError(f"Inference reset failed: {reset}")


def write_manifest(path: Path, url: str, deployment_id: str, environment: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(
            {
                "url": validate_url(url),
                "deployment_id": deployment_id,
                "environment": environment,
            },
            indent=2,
        )
        + "\n"
    )
