"""Shared endpoint checks and generated client configuration for our launchers."""

from __future__ import annotations

import asyncio
from pathlib import Path
from typing import Any, Literal, TypeVar

import aiohttp

from inference.endpoints import BackendManifest, HttpsOrigin, origin_text
from inference.generated.schemas import (
    HealthOut,
    StreamEnvelope,
    StreamPongResponse,
    StreamResetResponse,
    StreamResponse,
    StreamResultResponse,
)

ROOT = Path(__file__).resolve().parents[3]
Reply = TypeVar("Reply", bound=StreamEnvelope)


def write_endpoint(url: HttpsOrigin, configuration: Literal["Debug", "Release"]) -> Path:
    """The credential file cannot override these generated settings."""
    path = ROOT / f"apps/mobile/Configurations/{configuration}Endpoint.xcconfig"
    contents = "// Generated by Hand Wave tooling. Do not edit.\n"
    contents += f"HANDWAVE_INFERENCE_URL = {origin_text(url).replace('://', ':/$()/')}\n"
    temporary = path.with_suffix(".tmp")
    temporary.write_text(contents)
    temporary.replace(path)
    return path


async def verify_backend(backend: BackendManifest) -> None:
    """Wait for the real model, then test the protocol used by both clients."""
    url = origin_text(backend.url)
    async with (
        asyncio.timeout(180),
        aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=20)) as client,
    ):
        while True:
            try:
                async with client.get(f"{url}/v1/health") as response:
                    response.raise_for_status()
                    health = HealthOut.model_validate(await response.json())
                break
            except (aiohttp.ClientError, TimeoutError):
                await asyncio.sleep(2)
        if health != HealthOut(ok=True, deployment_id=backend.deployment_id):
            raise RuntimeError("The endpoint does not belong to this backend build")
        async with client.ws_connect(
            f"wss://{backend.url.host}/v1/stream", protocols=["handwave.v1"]
        ) as socket:
            if socket.protocol != "handwave.v1":
                raise RuntimeError("Inference service did not negotiate handwave.v1")
            sequence = 0

            async def exchange(reply: type[Reply], request: str, **fields: Any) -> Reply:
                nonlocal sequence
                sequence += 1
                await socket.send_json(
                    {"type": request, "sequence": sequence, "protocol": 1, **fields}
                )
                response = StreamResponse.model_validate(await socket.receive_json()).root
                if not isinstance(response, reply) or response.sequence != sequence:
                    raise RuntimeError(f"Inference {request} failed: {response}")
                return response

            context = {"idle_frames": 0, "missing_frames": 0, "segment_frames": 24, "motion": 0.0}
            await exchange(StreamPongResponse, "ping")
            frames = [[0.0] * 162 for _ in range(24)]
            result = await exchange(
                StreamResultResponse, "recognize", frames=frames, context=context, finalize=False
            )
            trace = result.result.trace
            if not trace.prediction or not trace.decode or trace.decode.buffered_frames != 24:
                raise RuntimeError("Inference smoke test did not execute the model")
            result = await exchange(
                StreamResultResponse, "recognize", context=context, finalize=True
            )
            if result.result.trace.finalize is None:
                raise RuntimeError("Inference finalize did not execute the decoder")
            await exchange(StreamResetResponse, "reset")


def write_manifest(path: Path, backend: BackendManifest) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(backend.model_dump_json(indent=2) + "\n")
