$schema: 'https://moonrepo.dev/schemas/tasks.json'

inheritedBy:
  languages: ['typescript', 'javascript']

fileGroups:
  sources:
    - 'src/**/*'
    - 'public/**/*'
  configs:
    - '*.config.{ts,js,mjs}'
    - '*.json'
    - '*.yml'
    - '*.yaml'
    - 'moon.yml'
    - 'tsconfig.json'
    - 'tsconfig.*.json'
    - 'package.json'
    - '/pnpm-lock.yaml'

tasks:
  format:
    command: 'pnpm exec oxfmt --write .'
    preset: 'utility'
    inputs:
      - '@group(sources)'
      - '@group(configs)'
      - '/.oxfmtrc.json'

  formatCheck:
    command: 'pnpm exec oxfmt --check .'
    inputs:
      - '@group(sources)'
      - '@group(configs)'
      - '/.oxfmtrc.json'

  lint:
    command: 'pnpm exec oxlint --no-error-on-unmatched-pattern .'
    inputs:
      - '@group(sources)'
      - '@group(configs)'
      - '.oxlintrc.json'
      - 'oxlint.config.*'

  lintFix:
    command: 'pnpm exec oxlint --fix --no-error-on-unmatched-pattern .'
    preset: 'utility'
    inputs:
      - '@group(sources)'
      - '@group(configs)'
      - '.oxlintrc.json'
      - 'oxlint.config.*'

  typecheck:
    command: 'pnpm exec tsc --noEmit --pretty'
    inputs:
      - '@group(sources)'
      - '@group(configs)'
