$schema: 'https://moonrepo.dev/schemas/tasks.json'

inheritedBy:
  languages: ['typescript', 'javascript']

fileGroups:
  sources:
    - 'src/**/*'
  configs:
    - '*.config.{ts,js,mjs}'
    - 'tsconfig.json'
    - 'tsconfig.*.json'
    - 'package.json'

tasks:
  format:
    command: 'pnpm exec oxfmt --write .'
    inputs:
      - '@group(sources)'
      - '@group(configs)'
      - '/.oxfmtrc.json'

  lint:
    command: 'pnpm exec eslint --fix --no-error-on-unmatched-pattern .'
    inputs:
      - '@group(sources)'
      - '@group(configs)'
      - 'eslint.config.*'

  typecheck:
    command: 'pnpm exec tsc --noEmit --pretty'
    inputs:
      - '@group(sources)'
      - '@group(configs)'
