$schema: 'https://moonrepo.dev/schemas/tasks.json'

inheritedBy:
  languages: ['python']

fileGroups:
  sources:
    - 'src/**/*.py'
    - 'tests/**/*.py'
    - '*.py'
  configs:
    - 'pyproject.toml'
    - 'uv.lock'
    - 'moon.yml'

tasks:
  format:
    command: 'uv run ruff format .'
    preset: 'utility'
    inputs:
      - '@group(sources)'
      - '@group(configs)'

  formatCheck:
    command: 'uv run ruff format --check .'
    inputs:
      - '@group(sources)'
      - '@group(configs)'

  lint:
    command: 'uv run ruff check .'
    inputs:
      - '@group(sources)'
      - '@group(configs)'

  lintFix:
    command: 'uv run ruff check --fix .'
    preset: 'utility'
    inputs:
      - '@group(sources)'
      - '@group(configs)'

  typecheck:
    command: 'uv run pyright'
    inputs:
      - '@group(sources)'
      - 'pyproject.toml'

  test:
    command: 'uv run pytest'
    inputs:
      - '@group(sources)'
      - '@group(configs)'
